version: "2.3.3"

services:
  mysql:
    image: mysql:8.0.34
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: stationSki
      MYSQL_USER:
      MYSQL_PASSWORD:
  gestion-station-ski-1.0:
    image: oussamasoltani/gestion-station-ski-1.0
    ports:
      - "8089:8089"
    depends_on:
      - mysql

  version: "2.3.3"

  services:
    mysqldb:
      image: mysql:8.0.34
      restart: unless-stopped
      env_file: ./.env
      environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_DATABASE=stationSki
      ports:
        - $MYSQLDB_LOCAL_PORT:3306
      volumes:
        - db:/var/lib/mysql
    app:
      depends_on:
        - mysqldb
      build: ./
      restart: on-failure
      env_file: ./.env
      ports:
        - $SPRING_LOCAL_PORT:8089
      environment:
        SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://localhost:3306/stationSki?createDatabaseIfNotExist=true",
          "spring.datasource.username" : "root",
          "spring.datasource.password" : "",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
        }'
      volumes:
        - .m2:/root/.m2
      stdin_open: true
      tty: true

  volumes:
    db: