version: "2.23.0"

services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=stationSki
      - MYSQLDB_ROOT_PASSWORD="admin"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysql
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "spring.datasource.url": "jdbc:mysql://mysql:3306/stationSki?createDatabaseIfNotExist=true",
          "spring.datasource.username": "${MYSQLDB_USER}",
          "spring.datasource.password": "${MYSQLDB_ROOT_PASSWORD}",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
        - app
    environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_DATABASE=stationSki
        - MYSQL_USER=root
        - MYSQL_PASSWORD=
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=grafana

  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana:rw

volumes:
  db:
  grafana-storage:
  nexus-data:
