version: "3.9"

services:
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQLDB_USER=root
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQLDB_ROOT_PASSWORD=
      - MYSQL_DATABASE=Devops
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - my-network
  app:
    depends_on:
      - mysql
    build: ./
    restart: on-failure
#    env_file: ./.env
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://192.168.1.50:3306/Devops?createDatabaseIfNotExist=true&useSSL=false",
        "spring.datasource.username" : "${MYSQLDB_USER}",
        "spring.datasource.password" : "${MYSQLDB_ROOT_PASSWORD}",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "none"
      }'
    volumes:
      - ./5NIDS2-G4-Projet1-1.0.jar:/syrinezouari-5nids2-g4-projet1.jar
    stdin_open: true
    tty: true
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - my-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - app
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=Devops
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=123456789
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    ports:
      - "3000:3000"
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - SonarQube_data:/opt/SonarQube/data
      - SonarQube_extensions:/opt/SonarQube/extensions
      - SonarQube_logs:/opt/SonarQube/logs
  nexus:
      image: sonatype/nexus3
      ports:
        - "8081:8081"
      volumes:
        - nexus-data:/nexus-data
networks:
  my-network:
volumes:
  db :
  grafana-storage:
  nexus-data:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
