version: "3.9"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
#    env_file: ./.env
    environment:
      - MYSQLDB_DOCKER_PORT=3306
      - MYSQLDB_ROOT_PASSWORD=
      - MYSQLDB_DATABASE=Devops
      - MYSQLDB_USER=Syrine
      - MYSQL_PASSWORD=
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
#    env_file: ./.env
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - my-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - app
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=Devops
      - MYSQL_USER=Syrine
      - MYSQL_PASSWORD=
networks:
  my-network:
volumes:
  db :
