  version: "1.29.2"  # Utilisez la version 3.3 de Docker Compose

  services:
    mysql:
      image: mysql:8.0.34
      restart: unless-stopped
      env_file: ./.env
      ports:
        - "3306:3306"
      #ports:
      #  - $MYSQLDB_LOCAL_PORT:3306
      environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_DATABASE=stationSki

      volumes:
        - db:/var/lib/mysql
    app:
      depends_on:
        - mysql
      build: ./
      restart: on-failure
      env_file: ./.env
      ports:
        - "8089:8089"
      environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://localhost:3306/stationSki?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
      volumes:
        - .m2:/root/.m2
      stdin_open: true
      tty: true

  volumes:
    db: