version: "2.3.3"

services:
  mysql:
    image: mysql:8.0.34
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: stationSki
      MYSQL_USER:
      MYSQL_PASSWORD:
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - "8089:8089"

  version: "2.3.3"

  services:
    mysqldb:
      image: mysql:8.0.34
      restart: unless-stopped
      env_file: ./.env
      environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_DATABASE=stationSki
      ports:
        - $MYSQLDB_LOCAL_PORT:3306
      volumes:
        - db:/var/lib/mysql
    app:
      depends_on:
        - mysqldb
      build: ./
      restart: on-failure
      env_file: ./.env
      ports:
        - "8089:8089"
      environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
      volumes:
        - .m2:/root/.m2
      stdin_open: true
      tty: true

  volumes:
    db: