version: "2.23.0"

services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE= stationSki
      - MYSQL_USER=
      - MYSQL_PASSWORD =
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysql
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "spring.datasource.url": "jdbc:mysql://mysql:3306/stationSki?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": "",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  sonarqube:
      image: sonarqube:latest
      ports:
        - "9000:9000"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    
  nexus:
    image: sonatype/nexus3:latest
    ports:
      - "8081:8081"
    volumes:
      - ./nexus-data:/nexus-data  # Montez un volume pour les données Nexus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
volumes:
  db :